name: golangci-lint
on:
  push:
    tags:
      - v2*
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          cache: 'true'
          go-version: stable
      - uses: golangci-lint run command/check.go command/install.go utils/datetime.go
        with:
          version: v2.12.2
